### ISSUE TITLE
Rename lazydfu-1.0-1.19+.jar without the + symbol

### ISSUE THREAD

**Issue by zachsai** [CorgiTaco-Archive/lazydfu#10]
Causing crash on forge 43.2.1
rename to something like" Rename lazydfu-1.0-1.19plus "

**Comment by EldraTheThird** [comment]
same issue :/ i love this mod

**Comment by CorgiTaco** [comment]
Here: https://www.curseforge.com/minecraft/mc-mods/lazy-dfu-forge/files/4327266
