### ISSUE TITLE
incompatibility symbol (red "x") in multiplayer menu

### ISSUE THREAD

**Issue by ghost** [CorgiTaco-Archive/lazydfu#5]
### To reproduce:
Ping a forge server in the multiplayer menu that does not have LazyDFU in its mods folder. The client will display a red "x" for incompatible even though you are able to join the server. Is this intended? Because I assumed LazyDFU is okay to run just client-side.

![redx](https://user-images.githubusercontent.com/82549089/135739922-70d17a95-0b29-4d92-91db-b8dbec349b09.JPG)

### Versions:
Forge 1.16.5-36,2,6
LazyDFU 0.1.3

### From clients latest.log:
_[02Oct2021 22:17:38.148] [Netty Client IO #3/INFO] [net.minecraftforge.fml.client.ClientHooks/CLIENTHOOKS]: Client has mods that are missing on server: [lazydfu]_

**Comment by Jonathing** [comment]
You should just be able to join regardless. The red X has always been a bit misleading on the server list screen.

**Comment by ghost** [comment]
@Jonathing @CorgiTaco from my understanding its fixable by changing one line of mod code to let forge know that it is a client-side only mod. Unless the mod supposed to be installed on servers? But if the mod doesn't actually do anything on the server it makes sense to make the mod client-side so this warning doesn't appear and the mod doesn't have to be installed server-side to resolve it...

**Comment by CorgiTaco** [comment]
@cpm9 DFU is on the server for both the integrated server(single player/client) and dedicated servers

**Comment by ghost** [comment]
> @cpm9 DFU is on the server for both the integrated server(single player/client) and dedicated servers

Great thanks for clarifying sorry to bother ya
